sudo: required

services:
- docker

install: true
script: true

deploy:
- provider: script
  skip_cleanup: true
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux